version: 0.1
env:
  secrets-manager
    TOKEN: sonarcloudtoken:TOKEN
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaplaygroundmjean01_mj-sonarcloud -Dsonar.organization=javaplaygroundmjean01 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
